version: 1
builder: alpine@3.21
commands:
    - (cd /root; GOCACHE=/tmp/cache go build -o ransomware main.go)
    - echo "./ransomware -source /root -target /mnt -detonate \"oiccflag{known_plaintext_attacks_are_fun_1231AfT}\"" > /root/.ash_history
    - (cd /root; ./ransomware -source /root -target /mnt -detonate "oiccflag{known_plaintext_attacks_are_fun_1231AfT}")
    - cat /root/.ash_history
files:
    - main.go
archives:
    - https://zlib.net/zlib-1.3.1.tar.gz
packages:
    - go
volumes:
    - ransomware,32,/mnt,persist
